# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-29 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersub',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='newslettersub',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
