# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-08 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSub',
        ),
    ]
