# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-24 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleShirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descriptions', models.CharField(max_length=255)),
                ('photo_url', models.FileField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.RenameModel(
            old_name='NewsletterUser',
            new_name='NewsletterSub',
        ),
    ]
