# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-24 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_auto_20180424_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleshirt',
            name='photo_url',
            field=models.FileField(blank=True, null=True, upload_to='sampleShirts/'),
        ),
    ]
