# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-30 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_auto_20180424_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersub',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='newslettersub',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
