# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-22 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_items', models.PositiveIntegerField(blank=True, null=True)),
                ('name_of_items', models.CharField(max_length=255)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_page.ShopShirts')),
            ],
        ),
    ]
