# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-23 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_page', '0002_auto_20180608_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo_url', models.FileField(blank=True, null=True, upload_to='shopShirts/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('size', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('EXTRA_LARGE', 'EXTRA_LARGE')], default='SMALL', max_length=10)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_page.Cart')),
            ],
        ),
        migrations.DeleteModel(
            name='ShopShirts',
        ),
    ]
