# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-12 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_page', '0002_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=255),
        ),
    ]
