# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-07 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_page', '0002_shoppingcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='shopshirts',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shopshirts',
            name='stock',
        ),
        migrations.AddField(
            model_name='shopshirts',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shopshirts',
            name='shirt_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='shopshirts',
            name='size',
            field=models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('EXTRA_LARGE', 'EXTRA_LARGE')], default='SMALL', max_length=10),
        ),
        migrations.AlterField(
            model_name='shopshirts',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
