# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-07 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_page', '0003_auto_20180607_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopshirts',
            name='shirt_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
