# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-23 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_page', '0004_auto_20180623_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
