# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-07 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_page', '0005_auto_20180607_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopshirts',
            name='shirt_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
