# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-07 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_page', '0006_auto_20180607_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopshirts',
            name='shirt_id',
        ),
        migrations.AddField(
            model_name='shopshirts',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
